version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    container_name: nodejs-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data:
